name: .NET Core Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ExploringActions1/ExploringActions1.csproj
      
    - name: Build
      run: dotnet build ExploringActions1/ExploringActions1.csproj --no-restore
      
    - name: Test
      run: dotnet test TestExploringActions1/TestExploringActions1.csproj --no-build --verbosity normal
